sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /kinect2/hd/points
    max_range: 5.0
    point_subsample: 1
    padding_scale: 1.0
    padding_offset: 0.01 # Kinect depth resolution (1.5mm at 50cm and 5cm at 5 m)
    max_update_rate: 1
    filtered_cloud_topic: filtered_cloud
